"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const health_routes_1 = __importDefault(require("./health.routes"));
const product_routes_1 = __importDefault(require("./product.routes"));
const vendor_routes_1 = __importDefault(require("./vendor.routes"));
const order_routes_1 = __importDefault(require("./order.routes"));
const delivery_routes_1 = __importDefault(require("./delivery.routes"));
const auth_routes_1 = __importDefault(require("./auth.routes"));
const router = (0, express_1.Router)();
router.use('/auth', auth_routes_1.default);
router.use('/health', health_routes_1.default);
router.use('/products', product_routes_1.default);
router.use('/vendors', vendor_routes_1.default);
router.use('/orders', order_routes_1.default);
router.use('/delivery', delivery_routes_1.default);
exports.default = router;
