"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const vendor_controller_1 = require("../controllers/vendor.controller");
const auth_middleware_1 = require("../middleware/auth.middleware");
const router = (0, express_1.Router)();
router.get('/', vendor_controller_1.getVendors);
router.get('/:id', vendor_controller_1.getVendorById);
router.put('/:id', auth_middleware_1.requireAuth, (0, auth_middleware_1.requireRole)(['admin', 'vendor']), vendor_controller_1.updateVendor);
exports.default = router;
